version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=hehor
      - MYSQL_DATABASE=flywithme_db
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      mysqldb:
        condition: service_started
    build: ./fwm-launcher
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/flywithme_db?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "hehor",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: